### ISSUE TITLE
Error regarding $search option in MongoDB.

### ISSUE THREAD

**Issue by LayaYerragunta** [jonathanscholtes/Travel-AI-Agent-React-FastAPI-and-Cosmos-DB-Vector-Store#1]
While debugging the program, I am receiving the error that $search option does not support in MongoDB and also operation failure in some packages like helpers.py.

![Screenshot 2024-09-09 142241](https://github.com/user-attachments/assets/e4b213a3-e809-44d0-8ff0-8dc5253a5865)

**Comment by jonathanscholtes** [comment]
Would you please share the command you ran to receive the error in your screenshot. In-addition, did you update the environment variables to point to an Azure Cosmos DB for MongoDB VCore instance?
